services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-container
    ports:
      - "7474:7474"  # Port for Neo4j Browser
      - "7687:7687"  # Port for Bolt Protocol
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_default__database=neo4j
    volumes:
      - ./data/data:/data  # To persist data
      - ./data/logs:/logs  # To persist logs
      - ./data/import:/var/lib/neo4j/import  # Import folder
      - ./data/plugins:/plugins  # Plugins folder
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474/"]
      interval: 30s
      timeout: 10s
      retries: 5
